version: "3"
services:
  chromium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 4gb
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_OPTIONS=--no-sandbox

  firefox:
    image: seleniarm/standalone-firefox:latest
    shm_size: 4gb
    depends_on:
      - seleniarm-hub
    environment:
      - SE_EVENT_BUS_HOST=seleniarm-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  seleniarm-hub:
    image: seleniarm/hub:latest
    container_name: seleniarm-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
